const types = {
  abs: 'number',
  changes: 'number',
  char: 'string',
  format: 'string',
  hex: 'string',
  instr: 'number | null',
  last_insert_rowid: 'number',
  length: 'number',
  like: 'number',
  likelihood: 'number',
  lower: 'string',
  ltrim: 'string',
  printf: 'string',
  quote: 'string',
  random: 'number',
  randomblob: 'Buffer',
  replace: 'string',
  round: 'number',
  rtrim: 'string',
  sign: 'number | null',
  substr: 'string',
  substring: 'string',
  total_changes: 'number',
  trim: 'string',
  typeof: 'string',
  unicode: 'number',
  upper: 'string',
  date: 'string',
  time: 'string',
  datetime: 'string',
  julianday: 'number',
  unixepoch: 'number',
  strftime: 'string',
  avg: 'number',
  count: 'number',
  group_concat: 'string',
  max: 'number | string | null',
  min: 'number | string | null',
  sum: 'number',
  total: 'number',
  row_number: 'number',
  rank: 'number',
  dense_rank: 'number',
  percent_rank: 'number',
  cume_dist: 'number',
  ntile: 'number',
  acos: 'number',
  acosh: 'number',
  asin: 'number',
  asinh: 'number',
  atan: 'number',
  atan2: 'number',
  atanh: 'number',
  ceil: 'number',
  ceiling: 'number',
  cos: 'number',
  cosh: 'number',
  degrees: 'number',
  exp: 'number',
  floor: 'number',
  ln: 'number',
  log: 'number',
  log10: 'number',
  log2: 'number',
  mod: 'number',
  pi: 'number',
  pow: 'number',
  power: 'number',
  radians: 'number',
  sin: 'number',
  sinh: 'number',
  sqrt: 'number',
  tan: 'number',
  tanh: 'number',
  trunc: 'number',
  json_array: 'Array<any>',
  json_array_length: 'number',
  json_object: '{ [key: string]: any }',
  json_type: 'string | null',
  json_valid: 'number',
  json_group_array: 'Array<any>',
  json_group_object: '{ [key: string]: any }'
}

export default types;
